<?php
	require('highlight-title.php');
	require('decoration-bg.php');
	require('decoration-sm.php');
	require('logo-list.php');
	require('number-text-item.php');
	require('contact.php');
	require('icon-link-text.php');
	require('title-text-button.php');
	require('title-text-button-G.php');
?>